language: php

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master

install:
  - composer install

before_script:
  - cd lavender/lavender
  - mysql -e 'create database testing;'
  - sed -i s/DB_DATABASE=null/DB_DATABASE=testing/ .env
  - sed -i s/DB_USERNAME=null/DB_USERNAME=root/ .env

script:
  - php artisan migrate:entity
  - php artisan migrate
  - php artisan db:seed --class=InstallLavender
