language: php

php:
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer create-project lavender-commerce/lavender

after_script:
  - php lavender/artisan migrate:entity
  - php lavender/artisan migrate
  - php lavender/artisan db:seed --class=InstallLavender
